---
title: "Operations Metrics"
author: "Jing"
date-modified: Oct. 12, 2023
---
Oeprational Week Metrics

This Operational Metrics Quarto records the changes, updates due to the requests from Connect Operational team or any changes in the Connect Recruitment data in GCP prod. All the changes /updates will be committed via git by Jing and approved and merged by Jake for the auto run via the pipeline GCP.

It is composed of two parts: 1. the pdf weekly Operational reports;
                             2. the data outputs on any updates (shown below) which are saved in the individual folders in Box: 
                                a. participants with cancer history (monthly), 
                                b. weekly log tables on the counts of study activities: blood collections, baseline survey completions, active/passive recruitment, response rate, incentive, refusal withdrawals/Data destructions requests, participants qualified for follow-up or analysis among verified participants of the ongoing Connect study recruitments.
                                c. the incentive records of University of Chicago site and other NORC sites;
                                d. the weekly lists of participants with refusal withdrawal/ data destruction requests (overall/by site) 
                                e. the report will be delivered to Connect_DCEG_only/Connect Reports_DCEG ONLY/Metric Reports_DCEG  and Connect_ALL/Connect Weekly Operations Metrics_ALL folder

